## Nivell 1

**Exercici 
1:**
Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un pandas Dataframe. Explora les dades que conté, i queda’t únicament amb les columnes que consideris rellevants.

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df=pd.DataFrame(pd.read_csv('DelayedFlights.csv'))

In [3]:
df.columns

Index(['Unnamed: 0', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime',
       'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum',
       'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [4]:
df.head(20)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
5,6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,...,3.0,7.0,0,N,0,10.0,0.0,0.0,0.0,47.0
6,10,2008,1,3,4,706.0,700,916.0,915,WN,...,5.0,19.0,0,N,0,NaN,NaN,NaN,NaN,NaN
7,11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,...,6.0,8.0,0,N,0,8.0,0.0,0.0,0.0,72.0
8,15,2008,1,3,4,1029.0,1020,1021.0,1010,WN,...,6.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
9,16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,...,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0
10,17,2008,1,3,4,754.0,745,940.0,955,WN,...,5.0,16.0,0,N,0,NaN,NaN,NaN,NaN,NaN
11,18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,...,4.0,9.0,0,N,0,0.0,0.0,0.0,0.0,16.0
12,19,2008,1,3,4,1416.0,1325,1512.0,1435,WN,...,2.0,5.0,0,N,0,12.0,0.0,0.0,0.0,25.0
13,21,2008,1,3,4,1657.0,1625,1754.0,1735,WN,...,5.0,5.0,0,N,0,7.0,0.0,0.0,0.0,12.0
14,22,2008,1,3,4,1900.0,1840,1956.0,1950,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
15,23,2008,1,3,4,1039.0,1030,1133.0,1140,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
16,25,2008,1,3,4,1520.0,1455,1619.0,1605,WN,...,2.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
17,26,2008,1,3,4,1422.0,1255,1657.0,1610,WN,...,6.0,6.0,0,N,0,40.0,0.0,0.0,0.0,7.0
18,27,2008,1,3,4,1954.0,1925,2239.0,2235,WN,...,3.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
19,30,2008,1,3,4,2107.0,1945,2334.0,2230,WN,...,6.0,7.0,0,N,0,5.0,0.0,0.0,0.0,59.0

In [5]:
columnes=list(df.columns)

In [6]:
for column in columnes:
    print('* '*6,f'{column} ','* '*6,'\n',df[column].unique()) #per imprimir els valors únics de totes les columnes

* * * * * *  Unnamed: 0  * * * * * *
 [      0       1       2 ... 7009718 7009726 7009727]
* * * * * *  Year  * * * * * *
 [2008]
* * * * * *  Month  * * * * * *
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
* * * * * *  DayofMonth  * * * * * *
 [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31  2  1]
* * * * * *  DayOfWeek  * * * * * *
 [4 5 6 7 1 2 3]
* * * * * *  DepTime  * * * * * *
 [2003.  754.  628. ...  502.  503.  425.]
* * * * * *  CRSDepTime  * * * * * *
 [1955  735  620 ... 2331   48  140]
* * * * * *  ArrTime  * * * * * *
 [2211. 1002.  804. ...  401.  437.  405.]
* * * * * *  CRSArrTime  * * * * * *
 [2225 1000  750 ...  305  334  147]
* * * * * *  UniqueCarrier  * * * * * *
 ['WN' 'XE' 'YV' 'OH' 'OO' 'UA' 'US' 'DL' 'EV' 'F9' 'FL' 'HA' 'MQ' 'NW'
 '9E' 'AA' 'AQ' 'AS' 'B6' 'CO']
* * * * * *  FlightNum  * * * * * *
 [ 335 3231  448 ... 6869 6870 5272]
* * * * * *  TailNum  * * * * * *
 ['N712SW' 'N772SW' 'N428WN' ... 'N75428' 'N75429' 'N78008']
* * * * * *  ActualElapsedTime  * * * * * *
 [ 128.   96.   90.  101.  240.  130.  121.   52.  228.  226.  123.   56.
   57.   54.   59.  155.  165.  147.  154.  146.  145.  135.  127.  153.
  150.  152.  163.  136.   69.   70.  143.   71.   99.   86.   65.   63.
  119.  134.   51.   75.   74.   83.   79.  256.  124.  148.  149.  275.
  196.  204.   98.  233.   66.   58.   64.   60.   73.  260.  245.  242.
  212.  235.  110.  109.   92.   91.  159.  174.  158.  252.  194.  208.
  295.   61.   68.   72.   82.  114.  164.  117.  175.  156.  157.  254.
  197.  219.  200.  186.  192.  187.  185.  193.  270.  182.   94.  100.
  113.   95.  144.  137.   46.   50.   47.  251.  126.  141.  129.  269.
  261.   80.   62.   55.  229.  244.  293.  237.   84.   76.   67.  140.
  133.  162.  103.  118.   88.   85.   87.   89.   81.  178.  171.  169.
  232.   97.  160.  215.  105.   53.  168.  209.  210.  277.  111.   78.
   77.   93.  132.  201.  115.  139.  125.  142.  102.  179.  227.  217.
  220.  151.  241.  180.  167.  206.  223.   49.   48.  161.  170.  122.
  106.  312.  176.  172.  177.  166.  104.  298.   44.  116.   41.  239.
  267.  231.  225.  230.  236.  234.  265.  276.  262.  120.  138.  286.
  287.  294.  300.  107.  221.  238.  224.  255.  268.  253.  296.  281.
  203.  334.  338.  131.  250.  190.  183.  173.  324.  222.  202.  205.
  319.  310.  189.  243.  191.  181.  188.  184.  284.  108.  112.  266.
  332.  337.  278.  216.   40.  282.  207.   nan   45.  195.   39.  299.
  274.   42.   38.  341.   43.  289.  308.  198.  320.  290.  301.  303.
  331.  350.  214.  199.  279.  246.  271.  259.  305.  213.  218.  288.
  273.  283.  272.  292.  264.  249.  318.  248.  247.  344.  339.  309.
  211.  342.  297.  316.  353.  336.  317.  367.  263.  285.  307.  311.
  372.  328.  315.  351.  321.  330.  314.  313.  357.  352.  291.  258.
  257.  304.  349.  302.  348.  340.  347.  343.  323.  280.  345.  326.
   37.  329.  327.  306.   36.  333.  360.  325.  322.  335.  355.  365.
   35.  368.   25.  374.  356.  346.  354.   33.   29.   32.   34.   30.
   28.   27.   31.  433.   26.   24.  388.  551.  538.  527.  571.  556.
  552.  523.  512.  540.  541.  495.  450.  447.  463.  476.  465.  478.
  454.  468.  457.  532.  528.  557.  566.  558.  536.  509.  517.  401.
  386.  375.  418.  481.  373.  376.  420.  405.  397.  381.  362.  366.
  384.  382.  378.  369.  408.  442.  436.  399.  435.  391.  394.  363.
  431.  425.  396.  419.  403.  412.  400.  387.  407.  423.  414.  424.
  379.  389.  430.  371.  390.  404.  402.  416.  385.  392.  370.  380.
  361.  434.  441.  445.  426.  448.  413.  452.  515.  411.  359.  449.
  364.  398.  377.  409.  395.  393.  421.  358.  422.  432.  415.  383.
  438.  406.  472.  440.  427.  444.  417.  410.  466.  437.  547.  594.
  619.  663.  514.  598.  616.  513.  601.  693.  584.  475.  606.  488.
  453.  623.  605.  489.  615.  499.  455.  486.  439.  459.  508.  526.
  497.  485.  502.  550.  504.  511.  490.  531.  429.  428.  491.  507.
  506.  562.  561.  564.  579.  543.  569.  559.  546.  539.  576.  583.
  482.  498.  461.  451.  443.   22.   21.   19.   23.   20.  479.  462.
  505.  567.  634.  473.  658.  646.  501.  645.  667.  635.  614.  467.
  661.  446.  624.  629.  621.  640.  484.  649.  664.  494.  537.  456.
  626.  480.  460.  609.  570.  662.  520.  611.  596.  589.  572.  588.
  607.  617.  521.  633.  487.  592.  612.   17.  533.  554.  524.  519.
  593.  471.  679.  500.  470.  510.  464.  565.  620.  595.  483.  627.
  648.  493.  631.  585.  587.  586.  549.  516.  535.  492.  542.  503.
  477.  563.  574.  560.  496.  534.   18.   15.  474.  653.  637.  630.
  697.  625.  670.  628.  666.  698.  651.  659.  469.  647.  657.  568.
  582.  613.  610.  525.  555.  529.  581.  458.  530.  578.  602.  604.
  522.  553.  727.  548.  580.   16.  577.  644.  642.  660.  682.  636.
  687.  686.  672.  711.  683.  518.  575.  599.  544.  573.  641.  669.
  597.  638.  591.  608.  600.  545.  622.  632.  681.  590.  618.  654.
  643.  639.  675.  776.  724.  650.  656.  750.   14.  603. 1114.  652.
  702.  790.]
* * * * * *  CRSElapsedTime  * * * * * *
 [150. 145.  90. 115. 250. 135.  50. 240.  70. 195. 190. 165. 170. 180.
 185. 130.  80. 100.  75.  95. 125.  55.  85. 275. 120. 160. 155. 285.
 210. 205. 110.  60.  65. 265. 260. 230. 175. 215. 200. 290. 140. 270.
 245. 105. 225. 235. 220. 255. 315. 300.  45. 280. 365. 355. 335. 345.
 340. 295. 370. 305. 310. 360. 330. 320. 350. 325.  71. 198.  84. 173.
  67. 134. 128. 108. 132. 174. 201. 182.  57. 103. 141. 129. 123.  58.
 101. 126. 214. 122. 149.  77.  63. 231.  20.  69.  79. 117.  73. 153.
 197. 162. 112.  62. 124. 137. 159. 243. 194.  86. 239. 193.  17. 184.
 144. 151. 127.  81. 104. 158. 139. 131.  19. 192. 181. 167. 209. 213.
  56. 163. 223. 154. 148. 111.  92. 161. 183. 188. 206. 142.  68. 107.
 106. 102. 147. 171. 156. 204. 146. 113. 118.  78. 168.  88.  82. 157.
 152.  89. 178. 172.  74. 187.  97.  87. 109.  83. 218. 169. 207.  94.
 133.  72.  64. 143. 189. 119. 164. 227.  93.  99.  98. 202. 114. 179.
 138.  59. 208. 136.  66.  53. 211.  43. 177.  54. 196.  52. 219.  49.
 199. 186.  47.  46.  76.  96. 203.  44. 121.  34.  48. 166.  91.  38.
 176.  61. 224. 116.  40.  39.  35.  51.  32. 191. 216.  42. 313.  41.
  36.  25. 217. 262.  37.  31.  26. 234. 246. 257.  30. 237. 244. 226.
  23.  33. 552. 556. 476. 474. 470. 471. 547. 548. 333. 324. 392. 396.
 338. 407. 404. 389. 394. 323. 321. 409. 395. 312. 386. 372. 383. 381.
 307. 406. 393. 248. 319. 329. 282. 277. 362. 328. 344. 348. 439. 465.
 279. 283. 343. 347. 299. 342. 314. 298. 296. 317. 375. 336. 316. 352.
 302. 301. 274. 366. 397. 441. 303. 331. 297. 294. 341. 351. 363. 308.
 361. 334. 332. 388. 390. 379. 382. 254. 268. 271. 251. 267. 269. 252.
 273. 266. 276. 287. 281. 242. 241. 288. 233. 238. 322. 326. 385. 318.
 403. 400. 380. 356. 391. 309. 371. 304. 286. 293. 359. 339. 284. 292.
 232. 354. 367. 236. 291. 289. 264. 258. 272. 263. 221. 249. 228. 253.
 229. 212. 261. 222. 337. 247. 377. 327. 475. 405. 357. 401. 399. 449.
 456. 259. 278. 349. 311. 306. 374. 413. 378. 423. 426. 402. 358. 384.
 256. 412. 353. 373. 369. 364. 346. 368. 420. 398. 421. 387. 524. 597.
 600. 512. 416. 425. 419. 455. 440.  29.   1. 461. 513. 523.  nan 510.
 415. 500. 435. 560.  28.  27. 417. 505. 376. 660. 450. 565. 418. 427.
 408. 414.  18.  -9.  16. 515. 458. 430. 490. 460. 410. -21.  24. 541.
 444. 601. 595. 525.  21. 585. 535. 575. 635. 602.  15. -25. -12. 481.
 533. 443. 584. 528. 511. 495. 549. 445.   8. 526. 448. 446. 463. -10.
 -18.  12. 531. 478. 472. 436. 452. 422. 577. 573. 529. 485. 480. 540.
  14. 437. 432.   9. 453. 462. 536. 605. 473. 514. 532. 477. 438. 468.
 579. 527. 520. 479. 442. 587. 522. 580. 411.   2. 542. 604.]
* * * * * *  AirTime  * * * * * *
 [1.160e+02 1.130e+02 7.600e+01 7.700e+01 8.700e+01 2.300e+02 1.060e+02
 1.070e+02 3.700e+01 2.130e+02 2.050e+02 1.100e+02 4.900e+01 4.700e+01
 5.000e+01 1.430e+02 1.550e+02 1.340e+02 1.400e+02 1.180e+02 1.140e+02
 1.380e+02 1.510e+02 1.440e+02 1.210e+02 5.900e+01 6.000e+01 8.100e+01
 9.700e+01 7.200e+01 5.400e+01 1.250e+02 1.040e+02 1.200e+02 3.900e+01
 3.600e+01 3.800e+01 6.500e+01 2.430e+02 9.100e+01 1.310e+02 1.270e+02
 1.350e+02 2.530e+02 1.780e+02 1.830e+02 1.770e+02 7.300e+01 2.210e+02
 4.600e+01 4.800e+01 4.300e+01 2.440e+02 1.950e+02 2.010e+02 7.900e+01
 8.800e+01 7.800e+01 8.500e+01 8.000e+01 1.470e+02 1.460e+02 1.500e+02
 2.320e+02 1.760e+02 1.790e+02 2.690e+02 4.200e+01 4.000e+01 4.100e+01
 4.500e+01 4.400e+01 9.000e+01 1.480e+02 9.500e+01 1.390e+02 1.300e+02
 1.360e+02 2.340e+02 1.750e+02 1.810e+02 1.690e+02 1.710e+02 1.680e+02
 2.570e+02 1.660e+02 7.400e+01 7.100e+01 1.320e+02 3.400e+01 3.200e+01
 2.370e+02 1.120e+02 2.450e+02 2.100e+02 2.180e+02 2.660e+02 2.310e+02
 2.220e+02 5.700e+01 5.500e+01 6.100e+01 5.600e+01 5.100e+01 1.260e+02
 1.220e+02 1.920e+02 1.290e+02 1.190e+02 7.500e+01 9.800e+01 7.000e+01
 6.900e+01 6.800e+01 6.600e+01 5.800e+01 6.200e+01 6.700e+01 6.400e+01
 1.570e+02 2.170e+02 5.300e+01 8.200e+01 2.030e+02 2.000e+02 8.600e+01
 1.590e+02 1.540e+02 1.560e+02 2.020e+02 6.300e+01 5.200e+01 1.410e+02
 8.400e+01 1.880e+02 1.230e+02 1.020e+02 8.300e+01 1.640e+02 1.620e+02
 1.960e+02 2.280e+02 2.140e+02 1.600e+02 1.870e+02 2.080e+02 1.490e+02
 9.600e+01 9.400e+01 1.330e+02 1.170e+02 1.090e+02 1.110e+02 1.150e+02
 2.250e+02 1.370e+02 2.910e+02 1.520e+02 1.530e+02 9.200e+01 1.240e+02
 1.280e+02 2.760e+02 3.500e+01 3.000e+01 3.100e+01 3.300e+01 1.610e+02
 1.050e+02 1.580e+02 1.000e+02 1.420e+02 2.700e+01 2.190e+02 2.150e+02
 2.160e+02 2.200e+02 2.230e+02 2.490e+02 2.560e+02 2.520e+02 2.590e+02
 2.650e+02 2.720e+02 2.470e+02 9.300e+01 2.070e+02 2.120e+02 2.090e+02
 1.080e+02 2.380e+02 2.580e+02 2.420e+02 2.740e+02 2.680e+02 2.670e+02
 2.600e+02 1.860e+02 1.850e+02 3.200e+02 1.930e+02 1.890e+02 1.700e+02
 2.040e+02 8.900e+01 1.450e+02 1.970e+02 3.080e+02 1.010e+02 3.050e+02
 1.030e+02 2.940e+02 2.790e+02 1.630e+02 1.650e+02 2.330e+02 1.940e+02
 1.720e+02 1.730e+02 9.900e+01 2.360e+02 2.350e+02 2.510e+02 3.180e+02
 3.240e+02 2.800e+01 1.910e+02 1.990e+02       nan 1.740e+02 2.900e+01
 1.800e+02 2.270e+02 2.060e+02 1.820e+02 2.860e+02 1.670e+02 3.250e+02
 2.710e+02 2.110e+02 2.870e+02 2.240e+02 2.980e+02 2.850e+02 2.920e+02
 3.310e+02 2.880e+02 2.540e+02 3.270e+02 2.500e+02 2.400e+02 1.980e+02
 2.770e+02 2.480e+02 2.610e+02 2.550e+02 2.640e+02 2.750e+02 2.800e+02
 2.780e+02 2.700e+02 2.620e+02 3.170e+02 3.030e+02 1.900e+02 3.290e+02
 2.630e+02 3.110e+02 3.100e+02 2.950e+02 3.510e+02 2.260e+02 2.290e+02
 2.460e+02 2.390e+02 2.810e+02 2.830e+02 3.440e+02 3.260e+02 3.150e+02
 2.930e+02 2.890e+02 3.360e+02 3.040e+02 2.970e+02 3.430e+02 3.410e+02
 2.410e+02 2.600e+01 3.160e+02 3.140e+02 2.820e+02 3.380e+02 2.500e+01
 1.840e+02 2.900e+02 3.300e+02 3.020e+02 3.340e+02 3.320e+02 3.280e+02
 3.130e+02 3.060e+02 3.120e+02 3.220e+02 2.840e+02 2.990e+02 2.730e+02
 3.000e+02 3.070e+02 3.210e+02 3.090e+02 3.190e+02 2.960e+02 3.350e+02
 3.010e+02 3.550e+02 3.450e+02 3.530e+02 3.580e+02 1.200e+01 3.420e+02
 3.390e+02 2.400e+01 3.000e+00 2.200e+01 2.300e+01 1.600e+01 1.400e+01
 2.000e+01 2.100e+01 1.800e+01 1.900e+01 1.700e+01 1.500e+01 7.000e+00
 1.100e+01 1.300e+01 1.000e+00 4.000e+00 2.000e+00 0.000e+00 9.000e+00
 1.000e+01 5.170e+02 5.150e+02 5.110e+02 5.250e+02 5.270e+02 5.280e+02
 5.050e+02 4.880e+02 5.030e+02 5.130e+02 4.700e+02 4.340e+02 4.280e+02
 4.440e+02 4.310e+02 4.470e+02 4.580e+02 4.540e+02 5.160e+02 5.070e+02
 5.220e+02 5.300e+02 5.180e+02 4.840e+02 4.980e+02 3.630e+02 3.690e+02
 3.760e+02 3.770e+02 3.710e+02 3.590e+02 3.400e+02 3.540e+02 3.520e+02
 3.720e+02 3.230e+02 3.840e+02 3.800e+02 3.670e+02 3.560e+02 3.870e+02
 3.620e+02 3.700e+02 3.900e+02 3.650e+02 3.790e+02 3.750e+02 3.730e+02
 3.480e+02 3.740e+02 3.330e+02 3.570e+02 3.500e+02 3.660e+02 3.980e+02
 3.490e+02 3.470e+02 4.170e+02 4.090e+02 4.220e+02 4.130e+02 4.300e+02
 4.150e+02 4.420e+02 4.490e+02 4.020e+02 4.190e+02 4.390e+02 3.460e+02
 3.680e+02 3.370e+02 3.780e+02 4.240e+02 4.200e+02 3.640e+02 3.600e+02
 3.850e+02 3.960e+02 4.000e+02 3.950e+02 3.810e+02 3.860e+02 3.880e+02
 4.260e+02 3.610e+02 3.890e+02 4.010e+02 4.040e+02 3.820e+02 3.970e+02
 3.930e+02 3.830e+02 4.860e+02 5.720e+02 5.690e+02 4.920e+02 5.680e+02
 5.600e+02 5.630e+02 5.760e+02 4.710e+02 5.890e+02 5.000e+02 5.810e+02
 4.790e+02 5.870e+02 4.770e+02 4.750e+02 4.630e+02 4.380e+02 4.120e+02
 4.900e+02 4.810e+02 4.640e+02 4.680e+02 4.830e+02 5.330e+02 4.720e+02
 4.850e+02 4.960e+02 4.070e+02 4.910e+02 5.060e+02 4.100e+02 5.380e+02
 5.340e+02 5.430e+02 5.370e+02 5.290e+02 5.410e+02 5.120e+02 5.390e+02
 5.480e+02 4.160e+02 4.140e+02 4.670e+02 4.890e+02 3.940e+02 3.990e+02
 4.510e+02 4.320e+02 8.000e+00 3.910e+02 4.740e+02 4.650e+02 4.940e+02
 6.050e+02 3.920e+02 5.190e+02 6.170e+02 6.210e+02 6.290e+02 6.160e+02
 4.110e+02 6.260e+02 6.070e+02 4.780e+02 6.360e+02 4.250e+02 6.000e+02
 4.730e+02 6.020e+02 5.940e+02 4.180e+02 6.060e+02 4.590e+02 6.310e+02
 4.080e+02 6.280e+02 4.270e+02 4.060e+02 4.230e+02 4.800e+02 5.700e+02
 4.450e+02 6.270e+02 5.830e+02 5.540e+02 5.490e+02 5.750e+02 5.920e+02
 5.790e+02 5.650e+02 5.850e+02 6.000e+00 5.460e+02 5.100e+02 5.040e+02
 4.480e+02 4.560e+02 4.950e+02 5.080e+02 4.430e+02 4.500e+02 4.400e+02
 4.360e+02 4.460e+02 4.330e+02 5.420e+02 5.840e+02 5.800e+02 5.710e+02
 4.530e+02 6.090e+02 5.740e+02 5.670e+02 5.590e+02 5.020e+02 4.370e+02
 4.620e+02 4.970e+02 4.990e+02 4.870e+02 4.550e+02 5.010e+02 4.760e+02
 4.820e+02 4.520e+02 5.400e+02 5.470e+02 5.350e+02 5.140e+02 5.450e+02
 5.500e+02 5.440e+02 4.690e+02 4.660e+02 6.420e+02 5.990e+02 6.390e+02
 4.930e+02 6.640e+02 6.490e+02 6.150e+02 6.440e+02 6.480e+02 6.120e+02
 5.730e+02 6.370e+02 6.200e+02 6.030e+02 4.610e+02 6.240e+02 6.220e+02
 6.190e+02 5.960e+02 5.640e+02 5.000e+00 5.310e+02 4.210e+02 4.410e+02
 4.600e+02 5.210e+02 5.260e+02 4.350e+02 4.050e+02 4.290e+02 4.030e+02
 5.560e+02 5.860e+02 5.610e+02 5.530e+02 5.770e+02 5.360e+02 4.570e+02
 5.780e+02 5.570e+02 5.520e+02 6.040e+02 6.180e+02 6.110e+02 6.410e+02
 6.340e+02 6.520e+02 6.450e+02 6.540e+02 6.550e+02 6.130e+02 6.320e+02
 6.510e+02 5.550e+02 5.620e+02 5.090e+02 5.660e+02 5.230e+02 5.950e+02
 6.010e+02 6.080e+02 6.230e+02 5.930e+02 5.580e+02 5.200e+02 5.970e+02
 5.900e+02 6.100e+02 5.240e+02 5.910e+02 5.980e+02 5.510e+02 5.880e+02
 5.320e+02 7.330e+02 1.091e+03 5.820e+02 6.140e+02 6.300e+02 6.350e+02]

* * * * * *  ArrDelay  * * * * * *
 [ -14.    2.   14. ...  880. 1279.  991.]
* * * * * *  DepDelay  * * * * * *
 [  8.  19.  34. ... 956. 810. 925.]
* * * * * *  Origin  * * * * * *
 ['IAD' 'IND' 'ISP' 'JAN' 'JAX' 'LAS' 'LAX' 'LBB' 'LIT' 'MAF' 'MCI' 'MCO'
 'MDW' 'MHT' 'MSY' 'OAK' 'OKC' 'OMA' 'ONT' 'ORF' 'PBI' 'PDX' 'PHL' 'PHX'
 'PIT' 'PVD' 'RDU' 'RNO' 'RSW' 'SAN' 'SAT' 'SDF' 'SEA' 'SFO' 'SJC' 'SLC'
 'SMF' 'SNA' 'STL' 'TPA' 'TUL' 'TUS' 'ABQ' 'ALB' 'AMA' 'AUS' 'BDL' 'BHM'
 'BNA' 'BOI' 'BUF' 'BUR' 'BWI' 'CLE' 'CMH' 'CRP' 'DAL' 'DEN' 'DTW' 'ELP'
 'FLL' 'GEG' 'HOU' 'HRL' 'ROC' 'ORD' 'EWR' 'SYR' 'IAH' 'CRW' 'FAT' 'COS'
 'MRY' 'LGB' 'BFL' 'EUG' 'ICT' 'MEM' 'BTV' 'MKE' 'LFT' 'BRO' 'PWM' 'MSP'
 'SRQ' 'CLT' 'CVG' 'GSO' 'SHV' 'DCA' 'TYS' 'GSP' 'RIC' 'DFW' 'BGR' 'DAY'
 'GRR' 'CHS' 'CAE' 'TLH' 'XNA' 'GPT' 'VPS' 'LGA' 'ATL' 'MSN' 'SAV' 'BTR'
 'LEX' 'LRD' 'MOB' 'MTJ' 'GRK' 'AEX' 'PNS' 'ABE' 'HSV' 'CHA' 'MFE' 'MLU'
 'DSM' 'MGM' 'AVL' 'LCH' 'BOS' 'MYR' 'CLL' 'DAB' 'ASE' 'ATW' 'BMI' 'CAK'
 'CID' 'CPR' 'EGE' 'FLG' 'FSD' 'FWA' 'GJT' 'GRB' 'HNL' 'KOA' 'LAN' 'LIH'
 'MBS' 'MDT' 'MFR' 'OGG' 'PSP' 'RAP' 'ROA' 'SBA' 'SBN' 'SPI' 'TEX' 'YUM'
 'AVP' 'CWA' 'DRO' 'ILM' 'ITO' 'JFK' 'TVC' 'HDN' 'SBP' 'CLD' 'HPN' 'MIA'
 'SGF' 'TRI' 'SUN' 'SGU' 'SLE' 'MSO' 'BZN' 'YKM' 'GTF' 'BIL' 'JAC' 'MOD'
 'FAR' 'GUC' 'AZO' 'PIA' 'MLI' 'LNK' 'FCA' 'IDA' 'BIS' 'PSC' 'COD' 'TWF'
 'RDM' 'HLN' 'RDD' 'PIH' 'EKO' 'LWS' 'SMX' 'ACV' 'OXR' 'CEC' 'CIC' 'PMD'
 'RFD' 'BTM' 'IYK' 'IPL' 'BLI' 'CDC' 'SJU' 'STT' 'ANC' 'STX' 'MLB' 'PHF'
 'PFN' 'FAY' 'AGS' 'GNV' 'ABY' 'DHN' 'EVV' 'FNT' 'OAJ' 'TOL' 'SWF' 'EWN'
 'MEI' 'GTR' 'LYH' 'HHH' 'EYW' 'VLD' 'CSG' 'ACY' 'FSM' 'MCN' 'CHO' 'FLO'
 'BQK' 'SCE' 'TUP' 'TYR' 'LAW' 'SPS' 'ABI' 'GGG' 'ACT' 'SJT' 'TXK' 'CMI'
 'ROW' 'RST' 'MQT' 'LSE' 'DBQ' 'GFK' 'MOT' 'DLH' 'SUX' 'PLN' 'BGM' 'ERI'
 'ALO' 'CMX' 'RHI' 'ELM' 'JNU' 'KTN' 'SIT' 'PSG' 'CDV' 'YAK' 'BRW' 'OME'
 'OTZ' 'BET' 'FAI' 'SCC' 'ADQ' 'WRG' 'ADK' 'PSE' 'BQN' 'BPT' 'RKS' 'GCC'
 'MKG' 'DLG' 'AKN' 'LWB' 'ACK' 'WYS' 'BJI' 'INL' 'GST' 'PUB' 'OTH' 'LMT'
 'ITH' 'HTS' 'PIR']
* * * * * *  Dest  * * * * * *
 ['TPA' 'BWI' 'JAX' 'LAS' 'MCO' 'MDW' 'PHX' 'FLL' 'PBI' 'RSW' 'HOU' 'BHM'
 'BNA' 'IND' 'PHL' 'ABQ' 'ALB' 'AMA' 'AUS' 'BDL' 'BOI' 'BUF' 'BUR' 'CLE'
 'CMH' 'DEN' 'ELP' 'GEG' 'IAD' 'ISP' 'LAX' 'LBB' 'LIT' 'MAF' 'MCI' 'MHT'
 'MSY' 'OAK' 'OKC' 'OMA' 'ONT' 'ORF' 'PDX' 'PIT' 'PVD' 'RDU' 'RNO' 'SAN'
 'SAT' 'SDF' 'SEA' 'SFO' 'SJC' 'SLC' 'SMF' 'SNA' 'STL' 'TUL' 'TUS' 'DAL'
 'DTW' 'JAN' 'HRL' 'CRP' 'EWR' 'IAH' 'ROC' 'MYR' 'GSO' 'SAV' 'RIC' 'COS'
 'FAT' 'MRY' 'LGB' 'BFL' 'EUG' 'ICT' 'CAE' 'DFW' 'DAY' 'MSP' 'GSP' 'MEM'
 'TYS' 'SHV' 'BTV' 'MFE' 'PWM' 'ATL' 'SYR' 'MKE' 'HSV' 'BTR' 'CHS' 'MSN'
 'LFT' 'LRD' 'SRQ' 'CLT' 'VPS' 'AVL' 'GPT' 'LGA' 'ABE' 'BGR' 'DCA' 'ORD'
 'GRR' 'MOB' 'PNS' 'CHA' 'MGM' 'CVG' 'GRK' 'PSP' 'TLH' 'LCH' 'BOS' 'BRO'
 'XNA' 'BPT' 'LEX' 'MTJ' 'AEX' 'MLU' 'DSM' 'CRW' 'CLL' 'ILM' 'JFK' 'ASE'
 'CPR' 'DRO' 'RAP' 'KOA' 'LIH' 'OGG' 'MDT' 'ROA' 'SPI' 'HNL' 'MFR' 'ATW'
 'BMI' 'CAK' 'CID' 'FSD' 'FWA' 'GRB' 'LAN' 'MBS' 'SBN' 'FLG' 'GJT' 'YUM'
 'EGE' 'ITO' 'AVP' 'CWA' 'TVC' 'SBP' 'SBA' 'COD' 'HDN' 'TEX' 'CLD' 'MLB'
 'SGF' 'MIA' 'HPN' 'TRI' 'SUN' 'SGU' 'TWF' 'IDA' 'MSO' 'BZN' 'YKM' 'SLE'
 'HLN' 'LWS' 'GTF' 'BIL' 'BTM' 'JAC' 'FCA' 'PSC' 'ACV' 'RDD' 'IPL' 'MOD'
 'PIA' 'LNK' 'GUC' 'AZO' 'FAR' 'MLI' 'PMD' 'BIS' 'PIH' 'EKO' 'RDM' 'BLI'
 'IYK' 'SMX' 'CEC' 'CIC' 'OXR' 'RFD' 'CDC' 'OGD' 'STT' 'SJU' 'ANC' 'STX'
 'DAB' 'PHF' 'MCN' 'VLD' 'CSG' 'SWF' 'BQK' 'MEI' 'FAY' 'EWN' 'SCE' 'DHN'
 'EYW' 'EVV' 'PFN' 'GNV' 'FNT' 'AGS' 'ABY' 'CHO' 'OAJ' 'FSM' 'FLO' 'HHH'
 'TOL' 'LYH' 'GTR' 'ACY' 'TUP' 'LAW' 'TYR' 'ABI' 'TXK' 'ACT' 'SPS' 'SJT'
 'GGG' 'CMI' 'ROW' 'MQT' 'RST' 'LSE' 'DBQ' 'DLH' 'GFK' 'MOT' 'RHI' 'SUX'
 'CMX' 'BGM' 'PLN' 'ERI' 'ALO' 'ELM' 'KTN' 'SIT' 'JNU' 'CDV' 'PSG' 'YAK'
 'WRG' 'FAI' 'OME' 'BRW' 'SCC' 'OTZ' 'BET' 'ADQ' 'ADK' 'PSE' 'BQN' 'GCC'
 'RKS' 'CYS' 'MKG' 'DLG' 'AKN' 'LWB' 'ACK' 'WYS' 'INL' 'BJI' 'GST' 'LMT'
 'OTH' 'ITH' 'HTS' 'PIR']
* * * * * *  Distance  * * * * * *
 [ 810  515  688 ...  902 1746  890]
* * * * * *  TaxiIn  * * * * * *
 [  4.   5.   3.   6.   7.   2.   9.   8.  40.  16.  11.  62.  23.  28.
  22.  14.  18.  25.  64.  21.  13.  10.  20.  19.  12.   1.  17.  32.
  27.  15.  39.  24.  33.  34.  nan  31.  35.  45.  37.  30.  29.  44.
  26.  36.  48.  89.  52.  41.  91.  54.  66.  65.  57.  47.  59.  43.
  49.  85. 123.  46. 132.  58.  50.  76.  70. 114.  42.  38.  99. 150.
   0.  81.  67.  55.  51. 105.  71. 125.  93.  96.  90.  87.  60. 143.
  88. 100.  61.  73. 115. 121.  86. 101. 145. 167. 133. 113.  56.  75.
  79.  92.  95. 146.  53.  97.  78.  83.  82.  63.  77.  80.  69.  68.
  84. 152. 126. 189. 151.  94. 120.  74.  72. 106. 128. 129. 107. 109.
 124. 163. 160. 136. 131. 154. 148. 117. 110. 111. 159. 135. 175. 147.
 141. 157. 176.  98. 138. 200. 122. 119. 207. 199. 103. 112. 104. 102.
 144. 137. 165. 174. 156. 149. 184. 130. 178. 116. 118. 134. 153. 158.
 225. 170. 240. 186. 197. 127. 140. 179. 139. 171. 108. 161. 173.]
* * * * * *  TaxiOut  * * * * * *
 [  8.  10.  17.   7.  19.   9.  16.   5.   6.  11.  12.  14.  15.  28.
  13.  22.  18.  24.  21.  30.  20.  32.  23.  85.  29.  52.  44.   4.
  33.  25.  26.  27.  50.   3.   1.  37.  42.  31.  35.  40.  38.  45.
  47.  39.  41.  34.  46.  36.  51.  49.   2.  61.  67.  48.  43.  64.
  66.  63.  59. 113.  78.  92.  90.  55.  58.  56.  79.  77.  69.  53.
  72.  62.  76.  65.  75.  57.  71.  73.  68.  60.  83.  54. 104. 107.
 101.  70.  93.  81.  94.  80.  74. 150.  86. 105.  97. 110. 127. 129.
  82. 108. 139. 115.  87.  84. 170. 154. 119. 102. 120. 178. 106. 103.
 151. 128. 112.  99.  88. 147. 131. 159. 124. 123. 109. 100. 137.  96.
 116.  95. 117.  89. 126. 138.  98.  91. 114. 157. 122. 118. 142. 133.
 164. 145. 149. 221. 153. 140. 163. 143. 162. 203. 167. 173. 130. 144.
 111. 125. 166. 177. 193. 190. 121. 141. 247. 266. 251. 233. 234. 262.
 318. 155. 287. 186. 298. 158. 383. 379. 320. 300. 306. 248. 168. 309.
 289. 271. 191. 218. 160. 165. 132. 152. 176. 134. 200.   0. 228. 278.
 288. 182. 244. 225. 206. 299. 257. 188. 322. 268. 148. 236. 208. 194.
 217. 201. 204. 136. 135. 156. 161. 146. 185. 202. 180. 172. 224. 209.
 220. 183. 187. 305. 330. 263. 210. 169. 199. 181. 195. 198. 205. 223.
 219. 227. 243. 184. 171. 192. 196. 175. 212. 238. 179. 241. 216. 189.
 197. 331. 335. 267. 226. 213. 231. 269. 229. 285. 256. 174. 246. 281.
 249. 222. 259. 237. 215. 211. 207. 214. 261. 364. 232. 326. 235. 230.
 274. 292. 290. 301. 282. 303. 276. 272. 240. 258. 280. 316. 345. 242.
 273. 245. 319. 337. 325. 252. 260. 277. 279. 264. 422. 291. 254. 284.
 250. 304. 356. 239. 265. 270. 283.  nan 308. 302. 327. 393. 336. 353.
 321. 342. 371. 255. 324. 386. 376. 312. 362. 286. 370.]
* * * * * *  Cancelled  * * * * * *
 [0 1]
* * * * * *  CancellationCode  * * * * * *
 ['N' 'A' 'B' 'C']
* * * * * *  Diverted  * * * * * *
 [0 1]
* * * * * *  CarrierDelay  * * * * * *
 [      nan 2.000e+00 1.000e+01 8.000e+00 3.000e+00 0.000e+00 1.200e+01
 7.000e+00 4.000e+01 5.000e+00 2.820e+02 2.600e+01 1.000e+00 1.100e+01
 1.500e+01 5.000e+01 2.300e+01 1.900e+01 1.800e+01 9.000e+00 4.800e+01
 1.700e+01 2.000e+01 4.000e+00 1.140e+02 6.000e+00 3.200e+01 1.300e+01
 1.600e+01 6.100e+01 2.500e+01 2.700e+01 1.400e+01 5.900e+01 6.000e+01
 2.100e+01 4.500e+01 3.800e+01 2.400e+01 1.920e+02 3.400e+01 3.900e+01
 2.200e+01 2.900e+01 6.900e+01 1.840e+02 2.850e+02 8.500e+01 3.000e+01
 3.100e+01 4.600e+01 3.300e+01 6.800e+01 3.700e+01 2.800e+01 3.600e+01
 7.500e+01 5.100e+01 5.800e+01 2.200e+02 5.500e+01 5.700e+01 3.500e+01
 4.300e+01 6.500e+01 8.200e+01 4.900e+01 4.700e+01 4.100e+01 1.000e+02
 6.300e+01 7.700e+01 5.200e+01 1.320e+02 4.400e+01 5.400e+01 9.200e+01
 2.660e+02 2.000e+02 8.600e+01 9.400e+01 6.400e+01 8.300e+01 9.000e+01
 6.600e+01 1.170e+02 9.800e+01 7.400e+01 1.220e+02 4.200e+01 1.680e+02
 1.560e+02 5.600e+01 6.700e+01 6.200e+01 1.050e+02 1.640e+02 1.200e+02
 9.700e+01 8.000e+01 5.300e+01 1.330e+02 1.030e+02 1.040e+02 1.960e+02
 1.020e+02 7.000e+01 7.200e+01 1.780e+02 1.380e+02 8.700e+01 1.520e+02
 2.690e+02 1.190e+02 1.670e+02 8.100e+01 7.600e+01 9.900e+01 8.800e+01
 1.270e+02 1.570e+02 1.910e+02 7.100e+01 1.260e+02 1.880e+02 7.300e+01
 9.100e+01 2.770e+02 1.750e+02 8.400e+01 1.110e+02 9.300e+01 2.500e+02
 1.290e+02 9.500e+01 1.090e+02 1.530e+02 1.120e+02 1.600e+02 7.900e+01
 1.440e+02 1.060e+02 1.450e+02 1.070e+02 2.160e+02 1.490e+02 1.010e+02
 1.480e+02 1.230e+02 8.900e+01 1.310e+02 1.500e+02 1.280e+02 9.600e+01
 7.800e+01 2.540e+02 1.240e+02 1.250e+02 1.350e+02 3.610e+02 1.100e+02
 1.080e+02 1.180e+02 1.150e+02 2.110e+02 3.470e+02 1.400e+02 1.810e+02
 2.620e+02 3.140e+02 1.130e+02 3.200e+02 2.080e+02 1.390e+02 1.420e+02
 1.590e+02 1.210e+02 1.370e+02 2.990e+02 1.990e+02 2.320e+02 2.020e+02
 2.330e+02 2.120e+02 2.930e+02 1.700e+02 2.100e+02 2.840e+02 1.360e+02
 1.820e+02 2.260e+02 1.850e+02 1.800e+02 4.310e+02 2.380e+02 2.610e+02
 2.420e+02 1.940e+02 1.930e+02 3.730e+02 4.120e+02 1.460e+02 1.650e+02
 1.620e+02 2.590e+02 2.580e+02 3.220e+02 1.430e+02 2.430e+02 1.760e+02
 2.480e+02 1.470e+02 1.740e+02 5.020e+02 2.240e+02 1.690e+02 1.410e+02
 2.250e+02 4.610e+02 2.750e+02 2.040e+02 2.190e+02 3.310e+02 3.110e+02
 1.160e+02 1.720e+02 2.410e+02 2.340e+02 1.630e+02 6.040e+02 2.830e+02
 2.950e+02 2.280e+02 2.370e+02 2.490e+02 1.900e+02 2.010e+02 2.210e+02
 2.520e+02 6.260e+02 2.360e+02 1.950e+02 3.480e+02 1.340e+02 1.830e+02
 1.770e+02 3.130e+02 4.510e+02 2.700e+02 2.790e+02 3.030e+02 4.060e+02
 4.190e+02 1.610e+02 3.120e+02 1.790e+02 4.160e+02 4.650e+02 1.540e+02
 6.520e+02 1.550e+02 1.730e+02 1.660e+02 1.970e+02 2.090e+02 2.130e+02
 2.070e+02 1.890e+02 1.300e+02 1.510e+02 2.140e+02 2.270e+02 2.310e+02
 1.980e+02 2.630e+02 2.600e+02 2.530e+02 2.300e+02 4.050e+02 2.550e+02
 1.860e+02 1.580e+02 2.050e+02 2.290e+02 2.030e+02 2.180e+02 3.910e+02
 3.240e+02 2.680e+02 4.090e+02 2.230e+02 3.370e+02 2.440e+02 3.500e+02
 3.260e+02 3.070e+02 3.100e+02 2.670e+02 3.300e+02 3.780e+02 1.870e+02
 2.810e+02 4.040e+02 2.170e+02 2.740e+02 3.620e+02 1.710e+02 2.960e+02
 2.060e+02 3.460e+02 2.220e+02 2.640e+02 3.430e+02 2.860e+02 2.150e+02
 2.920e+02 3.250e+02 4.520e+02 5.600e+02 3.060e+02 3.020e+02 6.060e+02
 4.000e+02 2.560e+02 2.350e+02 4.010e+02 5.780e+02 2.390e+02 2.470e+02
 2.460e+02 3.530e+02 2.720e+02 2.730e+02 2.400e+02 2.780e+02 3.170e+02
 3.320e+02 3.930e+02 2.710e+02 2.650e+02 3.870e+02 2.450e+02 6.320e+02
 2.880e+02 3.550e+02 3.660e+02 6.310e+02 3.340e+02 2.890e+02 3.560e+02
 1.032e+03 3.600e+02 2.570e+02 3.940e+02 4.500e+02 3.710e+02 3.850e+02
 3.760e+02 3.540e+02 2.510e+02 4.080e+02 3.150e+02 3.650e+02 4.930e+02
 3.000e+02 4.420e+02 2.910e+02 4.230e+02 3.350e+02 3.380e+02 5.550e+02
 2.900e+02 2.800e+02 3.840e+02 4.170e+02 3.570e+02 3.980e+02 4.330e+02
 3.700e+02 3.390e+02 4.790e+02 3.770e+02 4.430e+02 6.990e+02 3.990e+02
 2.870e+02 4.600e+02 6.130e+02 5.290e+02 5.750e+02 3.630e+02 6.830e+02
 5.560e+02 3.800e+02 4.530e+02 7.750e+02 3.920e+02 6.820e+02 6.770e+02
 6.280e+02 3.640e+02 8.560e+02 7.440e+02 4.100e+02 3.040e+02 3.720e+02
 5.850e+02 6.300e+02 5.000e+02 5.500e+02 4.750e+02 7.850e+02 4.740e+02
 5.610e+02 3.290e+02 6.880e+02 4.720e+02 4.410e+02 5.870e+02 7.810e+02
 4.680e+02 6.340e+02 3.580e+02 5.160e+02 5.300e+02 5.710e+02 3.510e+02
 6.090e+02 4.260e+02 4.860e+02 3.950e+02 6.620e+02 4.210e+02 4.900e+02
 5.810e+02 5.470e+02 4.540e+02 5.350e+02 7.430e+02 8.580e+02 3.520e+02
 4.130e+02 5.660e+02 9.030e+02 1.120e+03 8.880e+02 3.450e+02 5.820e+02
 3.410e+02 7.720e+02 7.640e+02 4.440e+02 7.600e+02 4.140e+02 1.017e+03
 3.050e+02 6.490e+02 8.650e+02 5.760e+02 6.630e+02 2.980e+02 3.820e+02
 7.770e+02 5.270e+02 3.090e+02 5.910e+02 6.790e+02 7.290e+02 5.450e+02
 3.160e+02 5.040e+02 4.340e+02 3.180e+02 4.580e+02 7.560e+02 4.490e+02
 1.094e+03 4.450e+02 3.740e+02 3.810e+02 3.080e+02 4.550e+02 8.050e+02
 9.730e+02 3.750e+02 7.700e+02 4.880e+02 8.770e+02 7.550e+02 1.036e+03
 3.400e+02 1.068e+03 9.630e+02 1.024e+03 4.980e+02 6.600e+02 4.030e+02
 4.250e+02 7.570e+02 3.690e+02 3.280e+02 4.020e+02 7.190e+02 7.000e+02
 1.014e+03 1.158e+03 5.330e+02 2.940e+02 4.840e+02 3.230e+02 3.360e+02
 3.900e+02 5.700e+02 5.950e+02 5.620e+02 3.270e+02 6.570e+02 3.590e+02
 4.560e+02 4.070e+02 4.300e+02 4.960e+02 4.370e+02 3.830e+02 3.190e+02
 8.380e+02 4.110e+02 5.070e+02 4.640e+02 3.880e+02 4.290e+02 4.800e+02
 1.089e+03 5.240e+02 3.420e+02 5.100e+02 5.400e+02 2.760e+02 3.010e+02
 7.100e+02 4.180e+02 4.870e+02 4.810e+02 3.210e+02 5.010e+02 5.390e+02
 4.240e+02 7.480e+02 4.760e+02 8.520e+02 6.030e+02 4.570e+02 6.400e+02
 6.750e+02 8.230e+02 4.590e+02 4.970e+02 7.760e+02 9.400e+02 4.770e+02
 3.890e+02 5.730e+02 8.290e+02 6.680e+02 5.230e+02 4.280e+02 5.590e+02
 3.860e+02 6.430e+02 8.760e+02 6.510e+02 6.350e+02 5.120e+02 7.590e+02
 2.970e+02 5.340e+02 3.440e+02 5.460e+02 9.470e+02 7.110e+02 5.830e+02
 1.351e+03 1.064e+03 1.065e+03 4.470e+02 5.970e+02 5.090e+02 6.180e+02
 8.990e+02 1.348e+03 4.690e+02 4.270e+02 6.230e+02 5.140e+02 3.670e+02
 9.820e+02 8.390e+02 9.410e+02 1.455e+03 7.710e+02 1.076e+03 1.200e+03
 1.107e+03 7.320e+02 5.740e+02 9.750e+02 7.340e+02 1.019e+03 9.550e+02
 4.350e+02 9.080e+02 7.270e+02 7.580e+02 6.730e+02 5.510e+02 6.110e+02
 7.400e+02 1.091e+03 9.060e+02 9.590e+02 5.360e+02 7.370e+02 9.180e+02
 4.830e+02 3.330e+02 3.680e+02 6.450e+02 8.590e+02 8.070e+02 8.620e+02
 6.410e+02 4.630e+02 3.960e+02 4.360e+02 1.061e+03 1.312e+03 1.086e+03
 4.990e+02 6.640e+02 5.150e+02 4.620e+02 8.810e+02 1.001e+03 4.380e+02
 3.490e+02 3.970e+02 5.430e+02 5.050e+02 4.220e+02 5.250e+02 5.530e+02
 7.050e+02 6.250e+02 4.480e+02 5.060e+02 9.900e+02 9.090e+02 6.890e+02
 4.460e+02 4.400e+02 4.670e+02 5.800e+02 4.200e+02 7.950e+02 7.900e+02
 5.380e+02 6.590e+02 5.410e+02 6.540e+02 8.030e+02 5.320e+02 1.090e+03
 5.130e+02 8.320e+02 5.960e+02 1.160e+03 7.940e+02 8.550e+02 9.790e+02
 7.120e+02 7.200e+02 1.011e+03 1.224e+03 5.580e+02 5.720e+02 6.660e+02
 7.180e+02 1.198e+03 5.180e+02 1.166e+03 6.810e+02 1.131e+03 7.330e+02
 7.080e+02 5.210e+02 8.310e+02 6.470e+02 7.610e+02 1.490e+03 7.530e+02
 4.910e+02 6.700e+02 6.420e+02 5.190e+02 5.640e+02 8.010e+02 5.200e+02
 5.900e+02 6.140e+02 7.260e+02 8.170e+02 1.026e+03 6.170e+02 1.084e+03
 6.000e+02 1.000e+03 1.172e+03 7.840e+02 7.380e+02 8.450e+02 9.040e+02
 3.790e+02 5.990e+02 6.050e+02 4.320e+02 6.120e+02 4.780e+02 6.200e+02
 5.420e+02 6.870e+02 4.920e+02 8.190e+02 7.030e+02 1.268e+03 5.790e+02
 8.510e+02 7.780e+02 7.130e+02 8.270e+02 5.440e+02 8.060e+02 8.840e+02
 6.980e+02 6.080e+02 7.070e+02 6.460e+02 1.139e+03 5.880e+02 1.249e+03
 1.015e+03 8.790e+02 1.044e+03 4.710e+02 1.075e+03 8.350e+02 6.850e+02
 1.046e+03 1.291e+03 5.930e+02 5.630e+02 7.220e+02 7.170e+02 1.542e+03
 7.690e+02 1.057e+03 1.395e+03 7.520e+02 2.436e+03 7.360e+02 6.150e+02
 6.530e+02 5.520e+02 5.680e+02 8.640e+02 1.104e+03 8.680e+02 6.010e+02
 8.340e+02 7.300e+02 6.220e+02 4.700e+02 6.670e+02 6.710e+02 6.270e+02
 4.940e+02 5.670e+02 8.630e+02 6.240e+02 9.320e+02 1.129e+03 7.630e+02
 6.290e+02 6.550e+02 7.990e+02 7.460e+02 7.140e+02 5.370e+02 1.203e+03
 1.292e+03 5.540e+02 1.258e+03 1.126e+03 1.111e+03 7.930e+02 1.951e+03
 8.860e+02 4.390e+02 4.850e+02 1.171e+03 1.141e+03 4.660e+02 9.280e+02
 6.440e+02 6.840e+02 1.096e+03 5.860e+02 8.700e+02 9.310e+02 1.043e+03
 5.490e+02 6.650e+02 6.690e+02 7.490e+02 6.330e+02 6.610e+02 8.980e+02
 1.707e+03 7.060e+02 9.110e+02 1.029e+03 9.100e+02 4.150e+02 9.570e+02
 1.040e+03 8.140e+02 5.940e+02 1.059e+03 1.165e+03 9.920e+02 1.344e+03
 9.700e+02 5.080e+02 1.186e+03 1.079e+03 1.055e+03 1.016e+03 6.780e+02
 7.670e+02 8.960e+02 8.830e+02 4.950e+02 7.230e+02 1.056e+03 4.890e+02
 7.890e+02 5.280e+02 7.020e+02 6.070e+02 6.960e+02 6.580e+02 5.770e+02
 8.100e+02 1.175e+03 1.082e+03 8.920e+02 9.600e+02 9.680e+02 6.480e+02
 6.760e+02 6.390e+02 6.940e+02 9.660e+02 5.030e+02 8.090e+02 9.450e+02
 8.210e+02 7.980e+02 7.040e+02 6.210e+02 1.510e+03 8.890e+02 8.370e+02
 8.720e+02 1.127e+03 6.900e+02 1.263e+03 9.140e+02 5.310e+02 8.220e+02
 7.510e+02 7.150e+02 6.910e+02 5.650e+02 8.900e+02 6.160e+02 1.045e+03
 4.730e+02 7.650e+02 6.020e+02 4.820e+02 5.920e+02 5.690e+02 5.220e+02
 1.124e+03 7.390e+02 7.500e+02 8.460e+02 5.170e+02 8.120e+02 1.359e+03
 5.840e+02 6.360e+02 6.930e+02 1.072e+03 7.010e+02 8.480e+02 9.020e+02
 8.000e+02 1.069e+03 1.020e+03 6.500e+02 1.286e+03 8.930e+02 8.420e+02
 7.790e+02 6.800e+02 5.570e+02 7.820e+02 1.168e+03 1.552e+03 1.382e+03
 9.330e+02 1.183e+03 8.490e+02 1.018e+03 6.720e+02 6.100e+02 1.369e+03
 6.970e+02 6.190e+02 8.130e+02 9.240e+02 9.540e+02 1.346e+03 1.146e+03
 9.560e+02 5.110e+02 1.230e+03 7.540e+02 7.470e+02 9.810e+02 8.610e+02
 1.081e+03 9.770e+02 9.880e+02 6.740e+02 8.600e+02 8.670e+02 1.194e+03
 9.500e+02 5.260e+02 1.003e+03 9.530e+02 8.470e+02 9.150e+02 8.690e+02
 1.092e+03 1.307e+03 8.870e+02 1.190e+03 8.540e+02 8.750e+02 1.038e+03
 7.740e+02 7.860e+02 9.970e+02 1.108e+03 7.350e+02 9.930e+02 1.170e+03
 9.740e+02 9.430e+02 7.210e+02 9.050e+02]
* * * * * *  WeatherDelay  * * * * * *
 [      nan 0.000e+00 2.400e+01 1.200e+01 2.200e+01 7.000e+00 2.500e+01
 1.350e+02 3.000e+00 1.000e+00 1.100e+01 4.000e+00 1.300e+01 5.000e+00
 8.100e+01 7.800e+01 7.200e+01 2.100e+01 8.000e+00 3.700e+01 5.500e+01
 1.570e+02 2.000e+00 2.020e+02 2.600e+01 6.800e+01 2.300e+01 4.800e+01
 3.200e+01 4.600e+01 3.300e+01 6.000e+01 5.400e+01 1.890e+02 1.980e+02
 1.000e+01 3.800e+01 7.000e+01 1.160e+02 3.100e+01 6.000e+00 1.800e+01
 7.700e+01 1.200e+02 6.300e+01 1.170e+02 5.000e+01 1.600e+01 1.700e+01
 3.000e+01 8.500e+01 4.300e+01 9.300e+01 1.500e+02 1.490e+02 4.000e+01
 7.600e+01 2.000e+01 1.180e+02 3.500e+01 6.600e+01 5.200e+01 1.130e+02
 1.500e+01 5.300e+01 4.200e+01 7.100e+01 3.600e+01 7.500e+01 1.400e+01
 2.220e+02 1.420e+02 6.500e+01 9.700e+01 2.330e+02 2.900e+01 8.000e+01
 5.600e+01 6.400e+01 3.400e+01 5.800e+01 8.700e+01 2.800e+01 9.000e+00
 6.700e+01 1.680e+02 4.900e+01 4.500e+01 1.000e+02 4.100e+01 1.480e+02
 1.050e+02 1.360e+02 1.610e+02 1.590e+02 1.670e+02 9.000e+01 1.710e+02
 1.660e+02 3.900e+01 4.400e+01 1.250e+02 1.900e+01 8.800e+01 1.750e+02
 7.400e+01 1.010e+02 8.900e+01 1.690e+02 8.400e+01 1.090e+02 1.390e+02
 4.700e+01 1.990e+02 2.230e+02 1.110e+02 2.700e+01 1.100e+02 5.900e+01
 5.100e+01 6.100e+01 1.800e+02 6.900e+01 9.100e+01 1.850e+02 1.430e+02
 8.200e+01 5.700e+01 1.070e+02 8.300e+01 9.200e+01 1.450e+02 2.300e+02
 1.080e+02 1.340e+02 1.460e+02 1.370e+02 1.920e+02 2.670e+02 1.630e+02
 1.950e+02 1.140e+02 1.270e+02 1.930e+02 1.330e+02 1.260e+02 1.820e+02
 9.400e+01 1.310e+02 1.440e+02 1.190e+02 9.500e+01 1.290e+02 1.400e+02
 9.800e+01 1.240e+02 2.450e+02 7.900e+01 1.150e+02 9.900e+01 1.860e+02
 1.410e+02 8.600e+01 2.310e+02 6.200e+01 1.740e+02 1.320e+02 2.660e+02
 1.880e+02 7.300e+01 4.060e+02 2.800e+02 3.430e+02 1.540e+02 2.350e+02
 1.030e+02 2.030e+02 1.210e+02 1.040e+02 2.080e+02 2.200e+02 1.600e+02
 1.910e+02 2.140e+02 1.760e+02 1.640e+02 2.010e+02 1.060e+02 1.020e+02
 1.280e+02 3.940e+02 3.490e+02 2.340e+02 2.180e+02 2.750e+02 3.440e+02
 1.510e+02 1.940e+02 1.230e+02 2.110e+02 1.120e+02 3.130e+02 1.550e+02
 2.050e+02 1.580e+02 1.520e+02 3.070e+02 2.120e+02 2.100e+02 2.250e+02
 2.940e+02 1.970e+02 1.380e+02 1.730e+02 1.830e+02 3.000e+02 3.100e+02
 1.220e+02 1.900e+02 2.980e+02 1.700e+02 2.420e+02 2.130e+02 2.650e+02
 2.850e+02 1.300e+02 2.150e+02 1.470e+02 4.090e+02 2.280e+02 2.930e+02
 2.210e+02 2.170e+02 3.340e+02 9.600e+01 2.400e+02 5.870e+02 1.840e+02
 1.720e+02 4.400e+02 2.730e+02 2.790e+02 2.430e+02 2.190e+02 2.060e+02
 1.650e+02 2.970e+02 3.050e+02 1.620e+02 1.960e+02 2.610e+02 1.530e+02
 3.700e+02 1.780e+02 2.840e+02 2.710e+02 2.480e+02 2.410e+02 2.550e+02
 2.590e+02 2.380e+02 3.390e+02 3.470e+02 3.250e+02 1.870e+02 1.770e+02
 2.040e+02 3.860e+02 2.680e+02 3.080e+02 2.830e+02 2.530e+02 3.640e+02
 2.000e+02 2.460e+02 2.580e+02 2.630e+02 4.880e+02 3.170e+02 2.870e+02
 3.010e+02 2.600e+02 1.810e+02 3.190e+02 2.690e+02 2.470e+02 3.850e+02
 2.920e+02 4.080e+02 3.310e+02 4.180e+02 4.580e+02 3.650e+02 2.820e+02
 3.480e+02 3.970e+02 3.770e+02 1.560e+02 4.220e+02 2.500e+02 2.370e+02
 2.560e+02 3.350e+02 2.490e+02 3.590e+02 1.790e+02 3.330e+02 2.890e+02

 4.130e+02]
* * * * * *  SecurityDelay  * * * * * *
 [ nan   0.  10.   8.  12.   3.   9.   6.  11.  14.   5.   2.  18.   7.
  22.  17.  20.  13.  16.  34.  19.   4.  15.   1.  45.  63.  48.  36.
  28.  21.  42.  31.  27.  88.  66.  80.  29.  33.  69.  24.  32.  54.
  26.  25.  60.  39.  78.  47.  43.  50.  23.  82.  37.  38. 136. 102.
  30.  40.  61.  46.  68.  41.  52.  58.  85.  35.  67.  57.  49.  44.
  89.  86.  65.  51.  53. 109.  72. 128.  62.  75.  64.  99. 149.  70.
  56.  97.  59. 120. 101. 115. 135. 112.  77.  55.  81.  87. 132. 108.
  74. 126.  98. 142.  92.  83.  76. 131.  71.  73.  91. 392. 175. 139.
 110. 134. 141. 155. 122. 107.  96. 111. 130. 123. 151. 147. 106. 280.
 229. 284. 100. 104. 156.  90. 178. 211.  95.  93. 209. 167. 191. 199.
 105. 140. 114. 124. 170. 150. 186. 121. 216. 113. 117. 357. 169.  79.
 193. 164. 254.]
* * * * * *  LateAircraftDelay  * * * * * *
 [      nan 3.200e+01 4.700e+01 7.200e+01 1.200e+01 1.600e+01 2.500e+01
 7.000e+00 5.900e+01 6.900e+01 2.900e+01 1.500e+01 2.200e+01 9.000e+00
 4.200e+01 1.900e+01 0.000e+00 2.000e+01 3.300e+01 5.800e+01 2.800e+01
 7.000e+01 3.100e+01 3.000e+01 2.000e+00 3.800e+01 4.000e+00 4.600e+01
 9.600e+01 5.100e+01 4.100e+01 5.600e+01 1.120e+02 1.400e+01 2.100e+01
 2.460e+02 3.900e+01 6.000e+00 8.000e+00 5.000e+00 2.700e+01 5.000e+01
 2.600e+01 6.400e+01 1.800e+01 9.400e+01 4.000e+01 3.500e+01 3.000e+00
 7.800e+01 5.200e+01 1.700e+01 2.400e+01 1.000e+01 1.100e+01 5.400e+01
 5.300e+01 1.300e+01 8.900e+01 4.900e+01 6.500e+01 6.200e+01 9.100e+01
 5.500e+01 1.000e+00 2.300e+01 3.400e+01 1.070e+02 9.900e+01 1.130e+02
 4.800e+01 7.400e+01 4.400e+01 8.700e+01 4.300e+01 8.500e+01 7.700e+01
 6.300e+01 9.000e+01 1.410e+02 1.870e+02 6.700e+01 1.560e+02 7.100e+01
 8.200e+01 1.020e+02 1.060e+02 4.500e+01 1.110e+02 7.300e+01 1.280e+02
 1.030e+02 6.800e+01 6.100e+01 9.500e+01 6.600e+01 3.700e+01 1.370e+02
 5.700e+01 8.300e+01 7.900e+01 9.800e+01 1.100e+02 7.600e+01 1.320e+02
 3.600e+01 1.430e+02 9.200e+01 8.100e+01 2.630e+02 7.500e+01 1.080e+02
 1.960e+02 1.230e+02 9.700e+01 1.660e+02 1.330e+02 1.220e+02 6.000e+01
 1.000e+02 1.090e+02 1.340e+02 1.040e+02 1.050e+02 1.210e+02 1.160e+02
 8.600e+01 1.630e+02 1.170e+02 1.580e+02 1.620e+02 1.820e+02 1.180e+02
 1.200e+02 9.300e+01 8.400e+01 8.000e+01 1.150e+02 1.720e+02 1.140e+02
 1.750e+02 2.010e+02 2.190e+02 2.370e+02 1.930e+02 2.140e+02 1.570e+02
 1.790e+02 1.610e+02 1.680e+02 1.500e+02 1.450e+02 1.700e+02 2.430e+02
 1.640e+02 1.440e+02 1.600e+02 1.850e+02 1.810e+02 1.530e+02 1.300e+02
 2.040e+02 1.650e+02 1.980e+02 1.250e+02 1.510e+02 8.800e+01 1.260e+02
 1.550e+02 1.190e+02 1.420e+02 1.290e+02 1.900e+02 2.100e+02 4.340e+02
 2.020e+02 2.130e+02 1.710e+02 1.760e+02 1.310e+02 1.010e+02 2.210e+02
 1.380e+02 2.220e+02 1.470e+02 2.060e+02 1.360e+02 1.480e+02 1.540e+02
 1.970e+02 2.250e+02 3.630e+02 2.070e+02 2.030e+02 1.400e+02 1.990e+02
 2.730e+02 1.690e+02 2.970e+02 1.240e+02 2.000e+02 1.590e+02 1.390e+02
 2.240e+02 1.910e+02 1.780e+02 1.270e+02 1.460e+02 1.770e+02 1.520e+02
 2.160e+02 2.270e+02 2.280e+02 1.350e+02 2.340e+02 2.080e+02 1.490e+02
 1.890e+02 1.840e+02 2.790e+02 2.380e+02 1.670e+02 2.320e+02 2.690e+02
 2.800e+02 2.170e+02 1.920e+02 1.800e+02 1.730e+02 1.880e+02 2.510e+02
 2.490e+02 1.740e+02 2.180e+02 3.290e+02 2.470e+02 2.550e+02 2.230e+02
 2.050e+02 1.830e+02 1.860e+02 2.110e+02 2.090e+02 2.360e+02 2.290e+02
 2.330e+02 3.300e+02 3.340e+02 3.440e+02 2.200e+02 1.950e+02 2.650e+02
 2.150e+02 2.400e+02 2.310e+02 3.180e+02 2.830e+02 3.110e+02 2.600e+02
 3.370e+02 2.870e+02 1.940e+02 3.570e+02 2.910e+02 2.120e+02 3.050e+02
 2.810e+02 2.410e+02 2.300e+02 2.920e+02 2.260e+02 2.640e+02 2.620e+02
 3.880e+02 2.350e+02 2.770e+02 2.750e+02 3.140e+02 2.480e+02 2.680e+02
 3.720e+02 4.160e+02 3.650e+02 3.460e+02 3.710e+02 2.520e+02 2.450e+02
 2.540e+02 3.030e+02 3.360e+02 2.940e+02 2.560e+02 2.610e+02 2.880e+02
 3.330e+02 3.480e+02 2.570e+02 3.910e+02 3.600e+02 2.580e+02 2.990e+02
 3.200e+02 4.330e+02 3.240e+02 2.660e+02 3.220e+02 2.420e+02 3.580e+02
 3.210e+02 2.780e+02 4.390e+02 2.390e+02 2.440e+02 3.010e+02 4.350e+02
 3.260e+02 4.040e+02 4.630e+02 2.590e+02 2.500e+02 3.060e+02 3.400e+02
 2.860e+02 4.790e+02 4.590e+02 4.030e+02 3.070e+02 2.950e+02 2.930e+02
 2.710e+02 2.900e+02 2.740e+02 3.230e+02 2.670e+02 3.320e+02 3.940e+02
 3.270e+02 2.720e+02 3.160e+02 4.840e+02 4.620e+02 3.410e+02 3.420e+02
 3.170e+02 7.990e+02 4.540e+02 3.820e+02 3.870e+02 3.520e+02 3.100e+02
 3.000e+02 3.970e+02 3.730e+02 2.530e+02 2.700e+02 3.430e+02 3.900e+02
 3.310e+02 3.250e+02 2.840e+02 3.190e+02 3.960e+02 3.780e+02 4.170e+02
 3.800e+02 3.390e+02 2.850e+02 3.020e+02 3.790e+02 3.640e+02 3.350e+02
 4.980e+02 4.140e+02 3.610e+02 3.740e+02 3.950e+02 3.620e+02 8.970e+02
 3.150e+02 2.760e+02 3.530e+02 3.830e+02 3.840e+02 4.470e+02 3.040e+02
 2.820e+02 3.120e+02 2.890e+02 4.110e+02 3.130e+02 4.000e+02 4.780e+02
 3.450e+02 4.400e+02 4.130e+02 4.550e+02 4.060e+02 3.850e+02 4.270e+02
 4.230e+02 4.460e+02 4.250e+02 3.560e+02 4.690e+02 3.380e+02 4.090e+02
 3.760e+02 3.090e+02 5.110e+02 2.960e+02 3.540e+02 4.150e+02 3.490e+02
 2.980e+02 3.280e+02 8.050e+02 3.500e+02 5.810e+02 5.440e+02 4.450e+02
 4.660e+02 4.290e+02 7.750e+02 3.670e+02 5.120e+02 6.550e+02 3.550e+02
 5.260e+02 5.520e+02 5.970e+02 3.080e+02 3.980e+02 8.890e+02 1.002e+03
 1.143e+03 4.300e+02 3.930e+02 3.770e+02 4.370e+02 3.690e+02 4.180e+02
 3.470e+02 4.310e+02 5.160e+02 3.590e+02 4.190e+02 3.680e+02 3.510e+02
 5.370e+02 9.250e+02 7.610e+02 1.254e+03 3.700e+02 6.080e+02 6.420e+02
 9.170e+02 5.130e+02 4.870e+02 8.450e+02 1.184e+03 4.100e+02 4.800e+02
 4.070e+02 4.020e+02 3.860e+02 3.750e+02 4.280e+02 4.750e+02 4.410e+02
 5.530e+02 4.010e+02 4.610e+02 3.810e+02 4.200e+02 4.890e+02 4.950e+02
 4.500e+02 7.160e+02 5.010e+02 4.480e+02 8.500e+02 4.730e+02 5.350e+02
 5.000e+02 4.120e+02 4.600e+02 5.320e+02 5.390e+02 7.840e+02 8.790e+02
 7.040e+02 3.660e+02 5.720e+02 3.920e+02 4.260e+02 4.210e+02 4.080e+02
 4.900e+02 4.440e+02 5.400e+02 5.930e+02 4.770e+02 4.680e+02 4.850e+02
 4.240e+02 5.620e+02 4.320e+02 6.780e+02 3.990e+02 8.080e+02 1.316e+03
 4.050e+02 4.420e+02 5.820e+02 5.730e+02 4.640e+02 5.070e+02 7.010e+02
 5.140e+02 7.590e+02 4.880e+02 6.480e+02 5.920e+02 5.430e+02 6.630e+02
 1.012e+03 6.860e+02 5.310e+02 3.890e+02 5.700e+02 6.020e+02 1.303e+03
 4.720e+02 4.360e+02 9.830e+02 4.960e+02 1.236e+03 4.530e+02 5.680e+02
 5.510e+02 4.700e+02 4.580e+02 4.760e+02 6.110e+02 4.430e+02 4.380e+02
 4.510e+02 6.380e+02 4.650e+02 4.490e+02 5.300e+02 5.330e+02 4.860e+02
 7.080e+02 5.150e+02 4.740e+02 5.280e+02 4.940e+02 6.610e+02 9.940e+02
 5.240e+02 6.160e+02 5.650e+02 6.520e+02 1.000e+03]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

In [8]:
df.groupby('Cancelled').count()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,Distance,TaxiIn,TaxiOut,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Cancelled,,,,,,,,,,,,,,,,,,,,,
0,1936125,1936125,1936125,1936125,1936125,1936125,1936125,1929648,1936125,1936125,...,1936125,1929648,1936125,1936125,1936125,1247488,1247488,1247488,1247488,1247488
1,633,633,633,633,633,633,633,0,633,633,...,633,0,178,633,633,0,0,0,0,0

In [9]:
df.groupby('Diverted').count()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Diverted,,,,,,,,,,,,,,,,,,,,,
0,1929004,1929004,1929004,1929004,1929004,1929004,1929004,1928371,1929004,1929004,...,1929004,1928371,1928549,1929004,1929004,1247488,1247488,1247488,1247488,1247488
1,7754,7754,7754,7754,7754,7754,7754,1277,7754,7754,...,7754,1277,7754,7754,7754,0,0,0,0,0

Pocs vols cancelats o desviats, més endavant reviso com evoluciona al netejar el dataframe.

In [10]:
del df['Unnamed: 0'] #columna idèntica al índex de posició, és innecesaria i l'esborro

In [11]:
df.drop('Year',axis=1,inplace=True) #No té sentit ja que totes les dades són del 2008
#2a manera de fer-ho, cal picar més codi!

In [12]:
df.head()

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1,3,4,2003.0,1955,2211.0,2225,WN,335,N712SW,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,3,4,754.0,735,1002.0,1000,WN,3231,N772SW,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,1,3,4,628.0,620,804.0,750,WN,448,N428WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,1,3,4,1940.0,1915,2121.0,2110,WN,378,N726SW,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN

**Exercici 
2;** 
Fes un informe complet del data set:
* Resumeix estadísticament les columnes d’interès
* Troba quantes dades faltants hi ha per columna
* Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...)
* Taula de les aerolínies amb més endarreriments acumulats
* Quins són els vols més llargs? I els més endarrerits?
Etc.

In [13]:
df.describe() #dona la informació estadística d'interès per a cada columna.

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,CRSElapsedTime,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.929648e+06,1.936758e+06,1.936758e+06,1.928371e+06,1.936560e+06,...,1.936758e+06,1.929648e+06,1.936303e+06,1.936758e+06,1.936758e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06
mean,6.111106e+00,1.575347e+01,3.984827e+00,1.518534e+03,1.467473e+03,1.610141e+03,1.634225e+03,2.184263e+03,1.333059e+02,1.343027e+02,...,7.656862e+02,6.812975e+00,1.823220e+01,3.268348e-04,4.003598e-03,1.917940e+01,3.703571e+00,1.502164e+01,9.013714e-02,2.529647e+01
std,3.482546e+00,8.776272e+00,1.995966e+00,4.504853e+02,4.247668e+02,5.481781e+02,4.646347e+02,1.944702e+03,7.206007e+01,7.134144e+01,...,5.744797e+02,5.273595e+00,1.433853e+01,1.807562e-02,6.314722e-02,4.354621e+01,2.149290e+01,3.383305e+01,2.022714e+00,4.205486e+01
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.400000e+01,-2.500000e+01,...,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.000000e+00,8.000000e+00,2.000000e+00,1.203000e+03,1.135000e+03,1.316000e+03,1.325000e+03,6.100000e+02,8.000000e+01,8.200000e+01,...,3.380000e+02,4.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.000000e+00,1.600000e+01,4.000000e+00,1.545000e+03,1.510000e+03,1.715000e+03,1.705000e+03,1.543000e+03,1.160000e+02,1.160000e+02,...,6.060000e+02,6.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,8.000000e+00
75%,9.000000e+00,2.300000e+01,6.000000e+00,1.900000e+03,1.815000e+03,2.030000e+03,2.014000e+03,3.422000e+03,1.650000e+02,1.650000e+02,...,9.980000e+02,8.000000e+00,2.100000e+01,0.000000e+00,0.000000e+00,2.100000e+01,0.000000e+00,1.500000e+01,0.000000e+00,3.300000e+01
max,1.200000e+01,3.100000e+01,7.000000e+00,2.400000e+03,2.359000e+03,2.400000e+03,2.400000e+03,9.742000e+03,1.114000e+03,6.600000e+02,...,4.962000e+03,2.400000e+02,4.220000e+02,1.000000e+00,1.000000e+00,2.436000e+03,1.352000e+03,1.357000e+03,3.920000e+02,1.316000e+03

In [14]:
df.isnull().sum() #suma els valors nuls de cada columna i els reporta.

Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

Mostra clarament que on hi manca força informació és en reportar els **minuts de retràs per cada causa**. De 1936758 entrades en fallen 689270 (35,6% del total).
Hi han alguns registres que li falta la **hora d'arribada real**, amb el que no es pot treballar amb les dades de retrasos. Elimino aquests registres (7110) ja que només suposen el 0,37% de les dades totals.

In [15]:
indexDel=list(df[df['ArrTime'].isnull()].index)#index de les línees que s'han de borrar
df.drop(indexDel, inplace=True)

In [16]:
df.isnull().sum() #suma els valors nuls de cada columna i els reporta.

Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                   0
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   3
ActualElapsedTime      1277
CRSElapsedTime            0
AirTime                1277
ArrDelay               1277
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                    0
TaxiOut                   0
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         682160
WeatherDelay         682160
NASDelay             682160
SecurityDelay        682160
LateAircraftDelay    682160
dtype: int64

Eliminem també les que falten dades de temps de vol o retràs en l'arrivada que manquen i són molt poques respecte el total.

In [17]:
indexDel=list(df[df['AirTime'].isnull()].index)#index de les línees que s'han de borrar
df.drop(indexDel, inplace=True)
df.isnull().sum()

Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                   0
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   3
ActualElapsedTime         0
CRSElapsedTime            0
AirTime                   0
ArrDelay                  0
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                    0
TaxiOut                   0
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         680883
WeatherDelay         680883
NASDelay             680883
SecurityDelay        680883
LateAircraftDelay    680883
dtype: int64

Canviem el valor del número d'avió (TailNum) a 'Unkown' pels 3 registres que no el tenen definit.

In [18]:
df['TailNum'].fillna(value='Unknown',inplace=True)
df.isnull().sum()

Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                   0
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   0
ActualElapsedTime         0
CRSElapsedTime            0
AirTime                   0
ArrDelay                  0
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                    0
TaxiOut                   0
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         680883
WeatherDelay         680883
NASDelay             680883
SecurityDelay        680883
LateAircraftDelay    680883
dtype: int64

In [19]:
df.groupby('Cancelled').count()

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Distance,TaxiIn,TaxiOut,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Cancelled,,,,,,,,,,,,,,,,,,,,,
0,1928371,1928371,1928371,1928371,1928371,1928371,1928371,1928371,1928371,1928371,...,1928371,1928371,1928371,1928371,1928371,1247488,1247488,1247488,1247488,1247488

In [20]:
df.groupby('Diverted').count()

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Diverted,,,,,,,,,,,,,,,,,,,,,
0,1928371,1928371,1928371,1928371,1928371,1928371,1928371,1928371,1928371,1928371,...,1928371,1928371,1928371,1928371,1928371,1247488,1247488,1247488,1247488,1247488

Al netejar el dataframe no queden vols cancelats. Es poden borrar totes les columnes referents a la cancelació i desviació de vols.

In [21]:
df.drop(['Cancelled','CancellationCode', 'Diverted'],axis=1,inplace=True)

Finalment generarem un sub-dataframe més petit (2/3 del  total) que contingui les dades de les causes del retràs per quan es vulgui estudiar quines són les causes dels retards.

In [22]:
df_cause=df.copy()
indexDel=list(df_cause[df_cause['NASDelay'].isnull()].index)#index de les línees que s'han de borrar
df_cause.drop(indexDel, inplace=True)
df_cause.isnull().sum()

Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
dtype: int64

In [23]:
#Com ja tenim un dataframe per estudiar especificament els valors de retràs reportats, borrem les olumnes d'aquest dataframe.
df.drop(['CarrierDelay','WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],axis=1,inplace=True)
df.isnull().sum()

Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
dtype: int64

### Crear Columnes noves

In [24]:
df['AverageSpeed']=df['Distance']/(df['AirTime']/60)#Dividim entre 60 perquè són minuts i volem per hora

In [25]:
df['AverageSpeed'].head(20)

0     418.965517
1     430.088496
2     406.578947
3     401.298701
4     474.482759
5     415.043478
6     468.679245
7     464.299065
8     262.702703
9     419.436620
10    435.804878
11    457.090909
12    269.387755
13    280.851064
14    269.387755
15    280.851064
16    264.000000
17    458.601399
18    423.096774
19    435.223881
Name: AverageSpeed, dtype: float64

In [26]:
df['Delayed']=df['ArrTime']>df['CRSArrTime'] #Generem columna de si hi ha retràs (=True) o no (False)

In [27]:
df['UniqueCarrier'].value_counts().head(3)

WN    376201
AA    190910
MQ    141223
Name: UniqueCarrier, dtype: int64

Les companyies amb més vols són WN (Southwest Airlines), AA (American Airlines) i MQ(American Eagle Airlines).

In [28]:
df_Carrier=df.groupby('UniqueCarrier')

In [29]:
df2=pd.DataFrame(df_Carrier['Delayed'].value_counts(True))
df2.xs(True, level='Delayed')[df2.xs(True, level='Delayed')['Delayed']==df2.xs(True, level='Delayed')['Delayed'].max()]

               Delayed
UniqueCarrier
HA             0.92773

In [30]:
df2.xs(True, level='Delayed')[df2.xs(True, level='Delayed')['Delayed']==df2.xs(True, level='Delayed')['Delayed'].min()]

                Delayed
UniqueCarrier
CO             0.780399

**La companyia que proporcionalment es retrassa més és HA** (Hawaiian Airlines) amb un 92,8% dels seus vols amb retràs.
**La companyia que proporcionalment es retrassa menys és CO** (Continental Express) amb un 78,0% dels seus vols amb retràs.

In [31]:
df2.xs(True, level='Delayed').sort_values('Delayed').iloc[0:3]# Les tres aerolinies més puntuals

                Delayed
UniqueCarrier
CO             0.780399
B6             0.785890
US             0.808452

In [32]:
df2.xs(True, level='Delayed').sort_values('Delayed',ascending=False).iloc[0:3]# Les tres aerolinies més impuntuals

                Delayed
UniqueCarrier
HA             0.927730
YV             0.906169
MQ             0.905185

In [33]:
df[df['UniqueCarrier'].isin(['HA', 'YV','MQ'])] #Data Frame amb les tres companyies més impuntuals.

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,AverageSpeed,Delayed
40993,1,1,2,2036.0,1741,2128.0,1856,YV,7138,N508MJ,...,101.0,152.0,175.0,ABE,ORD,654,5.0,6.0,388.514851,True
40994,1,1,2,1447.0,1230,1553.0,1347,YV,7263,N650ML,...,114.0,126.0,137.0,ABE,ORD,654,5.0,7.0,344.210526,True
40995,1,1,2,1211.0,1153,1323.0,1256,YV,7069,N455YV,...,36.0,27.0,18.0,ASE,DEN,125,6.0,30.0,208.333333,True
40996,1,1,2,930.0,900,1027.0,1011,YV,7074,N455YV,...,39.0,16.0,30.0,ASE,DEN,125,8.0,10.0,192.307692,True
40997,1,1,2,1346.0,1337,1448.0,1440,YV,7098,N434YV,...,38.0,8.0,9.0,ASE,DEN,125,8.0,16.0,197.368421,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1879355,12,18,4,1548.0,1535,1737.0,1730,MQ,4919,N712MQ,...,87.0,7.0,13.0,LGA,CMH,478,3.0,19.0,329.655172,True
1879356,12,19,5,1608.0,1535,1920.0,1730,MQ,4919,N715MQ,...,93.0,110.0,33.0,LGA,CMH,478,7.0,92.0,308.387097,True
1879357,12,21,7,1555.0,1535,1801.0,1730,MQ,4919,N710MQ,...,93.0,31.0,20.0,LGA,CMH,478,8.0,25.0,308.387097,True
1879358,12,22,1,1611.0,1535,1804.0,1730,MQ,4919,N724MQ,...,79.0,34.0,36.0,LGA,CMH,478,3.0,31.0,363.037975,True
1879359,12,24,3,1603.0,1535,1752.0,1730,MQ,4919,N702MQ,...,87.0,22.0,28.0,LGA,CMH,478,4.0,18.0,329.655172,True

In [34]:
listDist=df['Distance'].unique()

listDist.sort()
print(listDist[-5:])
 #els 10 vols més llargs

[4184 4213 4243 4502 4962]

In [35]:
df_Dist=pd.DataFrame(df.groupby('Distance')['FlightNum'].value_counts()).tail(10) 
df_Dist # Són els 10 # de vols amb les distàncies més llargues. També es detalla quants de cada un es van registrar a la última columna.

                    FlightNum
Distance FlightNum
4243     72                32
         1410               1
4502     1273             180
         1282             107
         851               67
         1561              59
         850               25
         1560              19
4962     15               265
         14                57

A continuació es detallen els trajectes del 3 vols més llargs, tots tres surten o arriben a HNL = Honolulu

In [36]:
df[df['Distance']==4962].groupby('Origin')['Dest'].value_counts()

Origin  Dest
EWR     HNL     265
HNL     EWR      57
Name: Dest, dtype: int64

In [37]:
df[df['Distance']==4502].groupby('Origin')['Dest'].value_counts()

Origin  Dest
ATL     HNL     306
HNL     ATL     151
Name: Dest, dtype: int64

In [38]:
df[df['Distance']==4243].groupby('Origin')['Dest'].value_counts()

Origin  Dest
HNL     ORD      91
ORD     HNL     206
Name: Dest, dtype: int64

In [39]:
df.sort_values('ArrDelay', ascending=False)[['ArrDelay','FlightNum','UniqueCarrier']].head() #Els 5 vols amb més retard
#Es detalla el retràs en la columna 'ArrDelay', el número de vol i la companyia

         ArrDelay  FlightNum UniqueCarrier
322516     2461.0        808            NW
686014     2453.0       1699            NW
839306     1951.0       1107            NW
1009553    1707.0       3538            MQ
1881639    1655.0        357            NW

**Exercici 
3:**
Exporta el data set net i amb les noves columnes a Excel.

In [48]:
df.to_excel('2008_flights_in_USA.xlsx',index=False)

ValueError: This sheet is too large! Your sheet size is: 1928371, 22 Max sheet size is: 1048576, 16384

In [40]:
df_1apart = df.iloc[:1000000,:].copy()#El dataset és massa gran per ser guardat a Excel, el dividim en 2.
df_2apart = df.iloc[1000000:, :].copy()

In [46]:
df_2apart.to_excel('2008_flights_in_USA__2apart.xlsx',index=False, engine='xlsxwriter')

Exception ignored in: <function ZipFile.__del__ at 0x0000027915F7D9D0>
Traceback (most recent call last):
  File "C:\Users\march\anaconda3\envs\notebook\lib\zipfile.py", line 1807, in __del__
  File "C:\Users\march\anaconda3\envs\notebook\lib\zipfile.py", line 1824, in close
ValueError: seek of closed file

In [47]:
df_1apart.to_excel('2008_flights_in_USA__1apart.xlsx',index=False, engine='xlsxwriter')

He penjat els dos arxius excel dintre d'un arxiu zip dividit en 8 perquè a Git-Hub no deixa guardar arxius superiors a 20Mb